apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: autosys
rules:
- apiGroups: [""]
  resources: ["podtemplates"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["pods/log", "pods/status"]
  verbs: ["get", "list", "watch"]
