apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: autosys
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: autosys
subjects:
- kind: ServiceAccount
  name: autosys
- kind: User
  name: ayashkov
